일별 카드 개수 조회 API 구현
boostcamp-2020/Project04-B-Whale pull request #132
Opened 2020-12-01 07:09 UTC by Park-SooYeon

# 일별 카드 개수 조회 API 구현

## 📎 해당 이슈

이슈 링크 (#110)

## 🛠 구현 내용 

- 일별 카드 개수 조회 API 구현
- API 및 service 함수를 테스트 하는 테스트 코드 작성

## 🙋‍ 리뷰어 참고 사항

SQL문에서 from 절에 서브 쿼리를 사용하는 것은 `인라인뷰`라고 부른다더군요.
DB에서 내부적으로 쿼리를 실행할 때, 일반적으로 인라인 뷰는 결국 join문으로 변경되서 실행이 된다고 합니다.
고로 인라인뷰를 썼을 때와 그냥 inner join을 사용했을 때의 성능차이가 나지 않는다는 결론이 나왔습니다.
실제로 explain 명령을 사용해서 실제 실행되는 쿼리를 확인해 보았을 때도 동일한 쿼리결과가 나왔었습니다.
그래서 join문을 이용해서 일별 카드 개수 조회 쿼리를 작성하였습니다:D

2020-12-01 07:29 UTC, dh00n commented on server/src/common/util/queryParser.js
> +        const value = keyValue[1];
```
const [key, value] = ele.split(delimiter);
```
로 작성해도 보기 좋을 것 같아유!!!!!

2020-12-01 07:31 UTC, dh00n approved these changes, later dismissed
👍👍👍

2020-12-01 07:34 UTC, Park-SooYeon commented on server/src/common/util/queryParser.js
> +        const value = keyValue[1];
헉 그러네요 저쪽은 왜 저렇게 할 생각을 못했었을까요ㅋㅋㅋ
commit b79c971
수정했습니다!

2020-12-01 08:12 UTC, youngxpepp requested changes
고생하셨어요! 쿼리 설명 감사합니다👏

2020-12-01 08:12 UTC, youngxpepp commented on server/src/service/CardService.js
> +            .innerJoin('card.list', 'list', 'list.board_id IN(:boardIds)', { boardIds })
```suggestion
            .innerJoin('card.list', 'list', 'list.board_id IN(:...boardIds)', { boardIds })
```
https://typeorm.io/#/select-query-builder/using-parameters-to-escape-data
위 문서 보면 `...` 을 붙여줘야 하는걸로 나오는데, 확인해보셨나요?

2020-12-01 08:12 UTC, youngxpepp commented on server/src/service/BoardService.js
> +            .where(`board.creator_id=:userId or user_id=:userId`, { userId })
```suggestion
            .where(`board.creator_id=:userId or invitation.user_id=:userId`, { userId })
```
invitation에 대한 조건이 빠진듯 해요

2020-12-01 08:12 UTC, youngxpepp commented on server/src/router/CardRouter.js
> +        const cardCounts = await cardService.getCardCountByPeriod(config);
하나의 트랜잭션에서 처리하는건 어떨까요?
나눈 이유가 궁금합니다!

2020-12-01 08:12 UTC, youngxpepp commented on server/src/service/CardService.js
> +            query = query.innerJoin('card.members', 'member', 'member.user_id=:userId', { userId });
여기가 me 조건인거죠?

2020-12-01 09:47 UTC, Park-SooYeon commented on server/src/router/CardRouter.js
> +        const cardCounts = await cardService.getCardCountByPeriod(config);
확장성을 고려해서 member가 me가 아닌 nickname일때에는 해당 nickname을 가지는 유저의 id값을 가져와서 분기해줄 수 있을 것 같다는 생각에 controller에서 처리를 했습니다!
만약, nickname을 통한 검색 기능이 필요하다면 이후에 해당 코드를 아래와 같이 사용하여 controller에서 처리를 해준다면 service함수에는 수정되지 않아도 될 것 같다는 생각이 들어서 이렇게 작성했습니다!
```javascript
if (member === 'me') {
    config.userId = userId;
} else (member !== '') {
    config.userId = await userService.getUserIdByName(member);
}
```

2020-12-01 09:49 UTC, Park-SooYeon commented on server/src/service/CardService.js
> +            query = query.innerJoin('card.members', 'member', 'member.user_id=:userId', { userId });
넵 me 조건에 의해 userId가 매개변수로 넘어왔을 때에만 해당 쿼리를 추가하도록 조건을 추가한것입니다.

2020-12-01 09:54 UTC, Park-SooYeon commented on server/src/service/CardService.js
> +            .innerJoin('card.list', 'list', 'list.board_id IN(:boardIds)', { boardIds })
cardRouter 테스트 코드 보면은 내가 만든 보드와 초대 받은 보드를 give로 하나씩 생성하고 테스트를 진행하고 있습니다.
두개의 보드가 있으니 boardIds가 [boardId1, boardId2]로 나올 것으로 예상했었습니다. 
테스트가 정상 통과가 되서 세퍼레이터를 안써도 문제는 없는 듯했는데 공식문서에서 안내해주는대로 사용하는게 좋을거 같네요.
수정하겠습니다:)

2020-12-01 10:15 UTC, Park-SooYeon commented on server/src/service/BoardService.js
> +            .where(`board.creator_id=:userId or user_id=:userId`, { userId })
commit 600a091
위의 리뷰 내용과 해당 리뷰 내용에 따라 코드 수정하였습니다:)

2020-12-01 11:17 UTC, youngxpepp commented on server/src/router/CardRouter.js
> +        const cardCounts = await cardService.getCardCountByPeriod(config);
확장성을 생각하셨군요👍
17번 라인이 실행되고 나서 트랜잭션이 끝나게 되는 순간 커넥션이 다른 요청에게 할당되면 어떡하죠?
컨트롤러 쪽 말고 서비스에서 분리하는건 어때요? 하나의 트랜잭션으로 묶을 수 있고, 확장성도 고려할 수 있을 것 같다는 생각이 듭니다ㅎㅎ

2020-12-01 11:17 UTC, youngxpepp commented on server/src/common/config/database/ConnectionOptionGenerator.js
> +                connectionOption.bigNumberStrings = false;
아깐 제대로 못 봤었는데 이건 어떠한 이유로 추가하신건지 궁금합니당😃

2020-12-01 12:18 UTC, Park-SooYeon commented on server/src/common/config/database/ConnectionOptionGenerator.js
> +                connectionOption.bigNumberStrings = false;
일단, 집계함수의 결과를 number type으로 받아들이기 위해서 위 속성을 사용했습니다.
count와 sum 같은 집계함수를 사용할 경우에는 쿼리문 결과를 가져올 때, .getMany()를 사용할 수 없고, .getRawMany()를 사용할 수 있고, 집계함수의 결과를 number type이 아닌 아래와 같이 string type으로 반환해 주더라구요...
``` json
{
    "dueDate": "2020-07-01",
    "count": "2"
}
```
제 생각에 집계함수를 사용할 경우에는 엄청 큰 값이 집계함수의 결과 값으로 주어질 수 있기때문에 typeORM이 기본적으로 집계함수의 결과를 string으로 반환해주는 것 같았습니다.🤔
카드 개수가 막 오버플로우가 발생할 정도로 엄청 큰 숫자로 반환되지는 않을 것 같고, 다른 부분에서도 엄청 큰 숫자를 쿼리문의 결과를 받아들일 경우도 없을거라고 생각해서 count의 값을 number type으로 일일히 바꿔주는 것보다 해당 속성을 추가하는 것이 더 효율적일 것이라고 생각해서 추가하게 되었습니다.
사실 response data의 count 값의 type이 string이여도 상관이 없었을까요.

2020-12-01 12:28 UTC, Park-SooYeon commented on server/src/router/CardRouter.js
> +        const cardCounts = await cardService.getCardCountByPeriod(config);
흠..확실히 하나의 트랜잭션에 DB select 하는 부분이 묶이지 않으면은 중간에 커넥션이 다른 요청에게 할당될수도 있겠네요🤔
서비스 쪽에서 분기를 해주게 되면은 서비스 함수의 매개변수로 현재 로그인된 userId를 필수로 받아야되는데 member가 me가 아닐때에는 해당 매개변수를 사용하는 일이 없으니 계속 받아올 필요가 있겠나라는 생각이 들어 controller에서 처리를 해줬는데 트랜잭션에 대해서는 생각을 못해봤네요.
한번 수정해보겠습니다!

2020-12-01 13:23 UTC, youngxpepp commented on server/src/common/config/database/ConnectionOptionGenerator.js
> +                connectionOption.bigNumberStrings = false;
꼼꼼함에 감탄하고 갑니다! 이런 설정이 있는줄 몰랐네요. 배워 갑니다👏

2020-12-01 13:31 UTC, Park-SooYeon commented on server/src/router/CardRouter.js
> +        const cardCounts = await cardService.getCardCountByPeriod(config);
commit aaee4e8
수정해보았습니다!
코드를 수정하다보니 트랜잭션 고려뿐만아니라 member값에 따른 분기는 비즈니스 로직으로 볼 수 있어 서비스가 해야하는 일이 맞았겠구나라는 생각이 들었네요..(아직 컨트롤러와 서비스의 역할이 잘 구분 하지 못해서 그런가봅니다😂)
그리고 컨트롤러는 단지 입력값 검증과 필요한 서비스 함수를 호출 하는 역할만 해야겠다고 생각하고 구현하려고 했으나.. validation을 어떤 방식으로 체크하는 것이 좋을지 고민이 되더라구요🤔
내일 validation을 어떤 방식으로 수행할지 얘기 나눠보면 좋을 것 같아요:)

2020-12-01 13:40 UTC, youngxpepp commented on server/src/router/CardRouter.js
> +        const cardCounts = await cardService.getCardCountByPeriod(config);
늦은 시간까지 고생하셨습니다🌝
validation 수행 방식은 내일 같이 얘기해봐요!

2020-12-01 13:41 UTC, youngxpepp submitted a review, later dismissed
섬세하게 코딩하시는 모습이 인상적입니다! 배워갑니당!

2020-12-02 00:16 UTC, dh00n submitted a review, later dismissed

2020-12-02 08:25 UTC, youngxpepp requested changes
진짜 고생하십니다😂
Validation 부분 한번 봐주실래요?

2020-12-02 08:25 UTC, youngxpepp commented on server/src/common/util/validator.js
> +    }
```suggestion
    await validateOrReject(classObject, { groups });
```
이렇게 하면 에러를 따로 던져주지 않아도 될 것 같아요✌️
ValidationError는 이미 'class-validator'에 정의가 되어 있어서 미들웨어인 errorHandler에서 처리하고 있습니다!
https://github.com/boostcamp-2020/Project04-B-Whale/blob/2a890211ab822d47472be513469b7538ad71483e/server/src/common/middleware/errorHandler.js#L13-L22

2020-12-02 08:47 UTC, Park-SooYeon commented on server/src/common/util/validator.js
> +    }
validator함수가 미들웨어로 처리되는게 아니여서 그런지 validateOrReject를 사용하면 에러 핸들링이 되지 않는다는 오류가 뜨더라구요..
그래서 validateOrReject에 의해 생성되는 에러를 핸들링 하려면 코드를 아래와 같이 작성해야하는데 try-catch에서 아무런 작업없이 에러를 던지기만하는 것은 린트 설정으로 막혀져있더라구요.
``` javascript
try {
    // ... 생략
     await validateOrReject(classObject, { groups });
} catch (e) {
    throw e;
}
```
차라리 린트 설정을 수정하는게 나았을까요?🤔

2020-12-02 09:57 UTC, youngxpepp commented on server/src/common/util/validator.js
> +    }
흠... 왜 처리가 안될까요
errorHandler 부분 디버깅 해주실 수 있나요?

2020-12-02 10:37 UTC, Park-SooYeon commented on server/src/common/util/validator.js
> +    }
다시 해봤는데 아무런 문제가 없네요..
코드 작성하면서 이것저것 같이 테스트했었는데 거기서 문제가 있었었나봅니다..😂
commit 90e7527 에 리뷰 반영했습니다!

2020-12-02 11:05 UTC, youngxpepp approved these changes
고생하셨습니다!

2020-12-02 12:34 UTC, dh00n approved these changes
👍👍👍👍👍

2020-12-02 12:42 UTC, merged