보드 상세 조회 API 구현
boostcamp-2020/Project04-B-Whale pull request #159
Opened 2020-12-03 08:00 UTC by dh00n

# 보드 상세 조회 API 구현

## 📎 해당 이슈

이슈 링크 (#27)

## 🛠 구현 내용 

- 단일보드 상세조회 api 구현
- 보드의 id값을 통하여 보드 상세 내용 조회

## 🙋‍ 리뷰어 참고 사항

2020-12-03 08:24 UTC, youngxpepp requested changes
join 하느라 고생하셨어요...
서비스에 필요한 것들 위주로 리뷰했습니다

2020-12-03 08:24 UTC, youngxpepp commented on server/src/service/BoardService.js
> +            .loadRelationCountAndMap('cards.commentCount', 'cards.comments')
loadRelationCountAndMap 이름만 봤을 때는 카드의 댓글 개수를 반환해주는 것 같은데 맞을까요?

2020-12-03 08:24 UTC, youngxpepp commented on server/src/service/BoardService.js
> +        }
```suggestion
        if (Array.isArray(boardDetail?.invitations)) {
            boardDetail.invitedUsers = boardDetail.invitations.map((v) => v.user);
            delete boardDetail.invitations;
        }
```
boardDetail의 유무는 위에서 검사하므로 중복 검사 안하셔도 될 듯합니다!ㅎㅎ
delete와 Object.assign을 활용하는 경우는 처음이네요! 나중에 써봐야겠어요👍
이 경우엔 delete 하는 대상이 너무 모호한 것 같아요. Object.assign이 target이 되는 boardDetail을 반환하긴 하지만, 찾아보지 않으면 모르거든요. 직관적으로 무엇을 할당할지, 삭제할지 코드를 작성하면 좀 더 이해하기 쉬울 것 같다는 느낌이 듭니다

2020-12-03 08:24 UTC, youngxpepp commented on server/src/service/BoardService.js
> +    }
서비스에 가입된 사용자라면 누구나 사용자를 특정 보드에 초대할 수 있게 되나요~? 
권한 검사가 필요한 듯 합니다. 초대를 하는 주체에 대한 검사가 보이지 않아요

2020-12-03 08:24 UTC, youngxpepp commented on server/src/service/BoardService.js
> +    async getDetailBoard(boardId) {
누구나 board를 조회할 수 있을까요?

2020-12-03 08:28 UTC, Park-SooYeon reviewed
커밋 단위가 작아서 읽기 좋네요:+1:

2020-12-03 08:28 UTC, Park-SooYeon commented on client/src/components/boardPage/TopMenu.js
> +            <div style={{ width: '50%' }}>
div 태그에 style을 사용하지 않고 Wrapper와 같은 하나의 컴포넌트를 만들어서 styled-component 방식으로 통일 시키는 것이 더 좋지 않을까요?👀

2020-12-03 08:28 UTC, Park-SooYeon commented on client/src/components/boardPage/ActivitySidebar.js
> +    animation-duration: 0.2s;
오 애니메이션이 있군요!
굳:+1:

2020-12-03 08:28 UTC, Park-SooYeon commented on client/src/components/boardPage/index.js
> +        console.log(data);
console.log가 남아있네요!

2020-12-03 08:28 UTC, Park-SooYeon commented on server/src/service/BoardService.js
> +        const boardDetail = await this.boardRepository
어마어마한 쿼리문 ㄷㄷ
고생하셨습니다:+1:

2020-12-03 08:28 UTC, Park-SooYeon commented on server/src/service/BoardService.js
>      }
``` javascript
async inviteUserIntoBoard(board, user) {
    const createInvitation = this.invitationRepository.create({board, user});
    await this.invitationRepository.save(createInvitation);
}
```
이렇게하면 더 코드량을 줄일 수 있지 않을까요?
근데 다만 매개변수명이 조금 애매해질수도 있을 것 같다는 생각이 들긴하네요🤔
동훈님 생각은 어떠신가요?

2020-12-03 08:28 UTC, Park-SooYeon commented on server/src/service/BoardService.js
> +            .loadRelationCountAndMap('cards.commentCount', 'cards.comments')
이 함수는 어떤 쿼리를 만들어주는 함수인가요?👀

2020-12-03 08:34 UTC, dh00n commented on server/src/service/BoardService.js
> +            .loadRelationCountAndMap('cards.commentCount', 'cards.comments')
맞습니다요 !~

2020-12-03 08:34 UTC, dh00n commented on server/src/service/BoardService.js
> +        }
리뷰사항 반영해보겠습니당 ㅎㅎ 🙃

2020-12-03 08:35 UTC, dh00n commented on server/src/service/BoardService.js
> +            .loadRelationCountAndMap('cards.commentCount', 'cards.comments')
comment들 개수 반환 함수입니더 !!

2020-12-03 08:35 UTC, Park-SooYeon commented on server/src/service/BoardService.js
> +    }
해당 보드에 참여중인 사람은 누구나 해당 보드에 초대할 수 있어야하지 않나요?-?
그렇다면 권한 검사는 해당 보드에 참여중인 사람이 맞는지를 검사 해야하는걸까요??

2020-12-03 08:36 UTC, youngxpepp commented on server/src/service/BoardService.js
> +    }
@Park-SooYeon 넵 해당 보드에 참여 중인지 검사해야 할 것 같다고 생각했습니다.

2020-12-03 08:37 UTC, dh00n commented on client/src/components/boardPage/TopMenu.js
> +            <div style={{ width: '50%' }}>
그냥 div로 묶는 작업이나 스타일이 얼마 없는 컴포넌트들 전부 변수 선언해서 사용하기 번거로워서 저 방식으로도 작성해 봤습니당
일관성 유지측면에서는 통일하는 것도 필요한거같아요 ㅠ !!

2020-12-03 08:46 UTC, dh00n commented on server/src/service/BoardService.js
> +    }
오 생각이 api 명세서만 보도 짜다가 생각이 짧았네요 ! 수정해보겠습니당

2020-12-03 09:26 UTC, dh00n commented on server/src/service/BoardService.js
> +    async getDetailBoard(boardId) {
@youngxpepp  리뷰사항 반영하였습니다 ~~~

2020-12-03 13:40 UTC, Park-SooYeon reviewed
고생하셨습니다!:D

2020-12-03 13:40 UTC, Park-SooYeon commented on server/src/service/BoardService.js
> +        }
getDetailBoard()랑 inviteUserIntoBoard()에서 권한 확인하는 부분이 동일한 것 같은데 함수로 분리해서 사용하면 더 좋을 것 같아요!:)

2020-12-03 13:40 UTC, Park-SooYeon commented on server/src/service/BoardService.js
> -        }
저는 보드 상세 조회 쿼리를 실행하기 전에 권한 체크를 하는 것이 더 좋을 것 같다는 생각이 드는데 보드 상세 조회 권한 검사 순서 변경이 된 이유가 무엇인가요?👀

2020-12-03 14:25 UTC, dh00n commented on server/src/service/BoardService.js
> -        }
권한검사를 할 때, 보드 아이디와 유저 아이디로 셀렉을 하는데 애초에 존재하지 않는 보드면 NotFound인지 Forbidden인지 구별할 수가 없고, 
존재하지 않는 보드면 권한검사 할 필요도 없기때문에 순서 측면에서는 어떤 상황이 더 자주 일어나는지? 를 고려해야 할 것같다는 생각이 드네요...🤔

2020-12-03 14:48 UTC, Park-SooYeon commented on server/src/service/BoardService.js
> -        }
아하! 저는 보드 조회 쿼리가 좀 더 복잡하기 때문에 비교적 간단한 쿼리인 권한 체크를 먼저 해주는 것이 좋을 것 같다고 생각을 했는데 동훈님 말씀도 일리가 있네요!
구현에 정답은 없을 것 같다는 생각이 들지만.. 의견 잘 듣고갑니다! 감사합니다!😁

2020-12-03 14:55 UTC, Park-SooYeon submitted a review, later dismissed
늦은 시간까지 수고하셨습니다!

2020-12-03 14:55 UTC, Park-SooYeon commented on server/src/service/BoardService.js
> +    async checkForbidden(hostId, boardId) {
checkCreatorOrInvitation과 같은 함수명을 사용하는 것이 좀 더 직관적이지 않을까요?👀

2020-12-03 15:04 UTC, dh00n commented on server/src/service/BoardService.js
> +    async checkForbidden(hostId, boardId) {
클린코드 책에서
한가지일만 하게하는 함수의 측면에서 함수명에 Or나 And는 피하라는 문구를 본거같아요
checkCreator / checkInvitation으로 더 잘게 나누는 것도 괜찮을 것 같습니다 ㅎㅎ 🙂

2020-12-03 15:11 UTC, youngxpepp commented on server/src/service/BoardService.js
> -        }
leftJoin을 하면 Outer Join일테고 심지어 join 개수도 만만치 않아 보여요.
만약 존재하는 보드이고 사용자에게 조회 권한이 없다면, 불필요하게 엄청난 비용의 쿼리를 실행하게 되지 않을까요?
권한검사 로직에 loadRelationIds 옵션 사용해서 creator의 id만 불러올 수 있어요. 이후 서버에서 creatorId를 비교해주면 좋을 것 같아요. boardId와 hostId를 and 연산으로 처리하지 않아도 됩니당. 그러면 보드가 존재하는지 확인할 수 있지 않을까요?

2020-12-03 15:36 UTC, dh00n commented on server/src/service/BoardService.js
> -        }
TypeORM을 난생처음 접해서 어떠한 옵션들이 있고 그러한 옵션들을 어느 부분에 적용시켜야 할 지 좀 어려워서, 관련부분 참고하여 공부해볼게여 
```
const board = await this.boardRepository.find({
            select: ['id'],
            where: { id: boardId },
        });
```
로 최초에 보드 존재 유무를 검사하면 쿼리는 한번 더 날리지만 보다 간단해 질 것 같습니다.
실무에서도 그렇다고 하지만 DB 성능적인 부분이 좀 고민되고 어려운 것 같네요

2020-12-04 01:51 UTC, Park-SooYeon approved these changes
고생하셨습니다:)

2020-12-04 01:54 UTC, youngxpepp approved these changes
많은 리뷰 반영하시느라 고생하셨습니다!

2020-12-04 01:59 UTC, merged