카드 수정 API 구현
boostcamp-2020/Project04-B-Whale pull request #212
Opened 2020-12-07 14:20 UTC by Park-SooYeon

# 카드 수정 API 구현

## 📎 해당 이슈

이슈 링크 (#35, #199)

## 🛠 구현 내용 

- 카드 수정 API 구현
- 요청 성공 시, 200 응답
- 현재 보드에 속한 리스트가 아닌 리스트로 이동힐 경우, 409 응답
- 카드 수정 권한이 없을 경우, 403 응답
- 수정할 카드를 찾을 수 없는 경우, 404 응답

## 🙋‍ 리뷰어 참고 사항 

현재 보드에 속한 리스트가 아닌 리스트로 이동힐 경우 어떤 응답이 좋을지 고민하다가..🤔
request body의 list id의 값이 잘못된 경우고 요청 수정 없이 동일한 요청을 보내지 말라는 의미를 가진 것이 400 응답이라 생각하여 400 응답으로 했었습니다.
그러나 좀 더 고민해보니 카드가 속하는 리스트가 보드에 속하지 않는 것은 서버가 가진 데이터의 상태와 충돌하는 것으로 볼 수도 있을 것 같아 409 응답이 적절할 것이라고 생각하여 409 응답으로 수정했습니다.
다른 분들은 어떤 응답이 적절할 것 같다고 생각하시나요? 다른 분들 의견이 궁금합니다.👀

2020-12-07 17:08 UTC, youngxpepp requested changes
고생하셨습니다! validator 잘 만들어 주셔서 감사합니다ㅎㅎ👍
궁금한 점이 있어서 질문 남겼어요!

2020-12-07 17:08 UTC, youngxpepp commented on server/src/dao/CustomBoardRepository.js
> +    async checkAccess({ boardId, userId }) {
데이터베이스에 직접 접근하는 계층이다 보니까, find exist count 등의 네이밍을 많이 사용하더라구요.
좀 더 적합한 메소드 이름이 없을까요?

2020-12-07 17:08 UTC, youngxpepp commented on server/src/dto/CardDto.js
> +    listId;
밑에 있는거랑 어떤 차이가 있나요? 중복해서 필드를 선언한 이유가 있을까요?

2020-12-07 17:08 UTC, youngxpepp commented on server/src/service/CardService.js
> +        const { board } = await this.listRepository.findOne(list.id, { relations: ['board'] });
하나의 쿼리로 합쳐도 될 것 같다는 생각이 드는데, 쿼리 빌더 사용하시는건 어때욥?

2020-12-07 17:27 UTC, dh00n commented on server/src/dao/CustomBoardRepository.js
> +        return isAuth.length !== 0;
똑같이 동작하는 메서드 만들어 놨었는데 또 만드셧네요 ,,!😥

2020-12-07 17:31 UTC, youngxpepp commented on server/src/dao/CustomBoardRepository.js
> +        return isAuth.length !== 0;
동훈님 메서드는 service 계층에 있지 않아요? 아마 밑으로 내리신거 같은데 아닌감

2020-12-08 01:36 UTC, Park-SooYeon commented on server/src/dao/CustomBoardRepository.js
> +    async checkAccess({ boardId, userId }) {
보드에 참여중인 유저인지 체크하는거니까.. isExistUserInBoard와 같은 함수명을 사용하는 것이 좀 더 직관적일까요?🤔

2020-12-08 01:44 UTC, youngxpepp commented on server/src/dao/CustomBoardRepository.js
> +    async checkAccess({ boardId, userId }) {
https://jojoldu.tistory.com/516
이런건 참조해보니까 JPA에선 repository를 통해 뭔가 있는지 없는지 확인하려면 exists라는 키워드를 사용하네요!

2020-12-08 01:55 UTC, Park-SooYeon commented on server/src/dto/CardDto.js
> +    listId;
class-validator에서 ValidateIf 예제는 이렇게 사용하고 있더라구요..
그리고 위가 엔티티의 기본이 되는 값이고 아래 쪽에서 엔티티의 기본이 되는 값에 따라 어떤 validation 옵션을 어디에 적용시킬 건지 체크하는거라고 이해해서 이렇게 작성했습니다.
근데 다시보니 결국엔 IsOptional과 차이가 없는 것 같네요..ValidateIf에 대해 좀 더 찾아봐야겠습니다.🤔

2020-12-08 01:56 UTC, Park-SooYeon commented on server/src/dao/CustomBoardRepository.js
> +        return isAuth.length !== 0;
아 저는 권한 체크할 때, boolean 값을 반환해주려고 새로 만들었어요!

2020-12-08 01:56 UTC, Park-SooYeon commented on server/src/service/CardService.js
> +        const { board } = await this.listRepository.findOne(list.id, { relations: ['board'] });
쿼리빌더를 사용해도 어짜피 조인이 두번 일어나니 차이가 없을 것 같다고 생각했어요.
조인이 한번씩 수행되는 쿼리를 두번 호출하기보다는 조인이 두번 수행되는 한방 쿼리로 하는 것이 좀 더 효율적이였을까요?🤔

2020-12-08 02:04 UTC, youngxpepp commented on server/src/dto/CardDto.js
> +    listId;
혹시 참조한 문서 알려주실 수 있을까요? 필드의 중복선언이 신기하네요

2020-12-08 02:08 UTC, youngxpepp commented on server/src/service/CardService.js
> +        const { board } = await this.listRepository.findOne(list.id, { relations: ['board'] });
네트워크 비용이 더 클거 같다는 생각이 들어요.
114번 째 라인이 완료가 되어야 115번이 실행되는 구조라서, 한방 쿼리가 효율적이라고 생각했습니다ㅎㅎ
두 번 조인하는게 같다면, 네트워크 비용을 줄이는게 좋을거 같아요!

2020-12-08 02:14 UTC, Park-SooYeon commented on server/src/dto/CardDto.js
> +    listId;
https://github.com/typestack/class-validator
여기서 참조했습니다! 예제에서는 다른 필드명을 사용하고있어요.

2020-12-08 02:53 UTC, youngxpepp commented
409에 대한 의견을 안 드렸었네요. 409 코드는 수연님 덕분에 처음 알았어요. 좋다고 생각합니다ㅎㅎ

2020-12-08 03:01 UTC, dh00n commented
만약 저희 서비스가 현재 보드에 속한 리스트가 아닌 타 보드의 리스트로 이동하는 기능 지원을 안한다면 
저도 409가 맞다고 생각합니다 ㅎㅎ

2020-12-08 03:17 UTC, Park-SooYeon commented on server/src/dao/CustomBoardRepository.js
> +    async checkAccess({ boardId, userId }) {
commit ab84c23
아래 쿼리 빌더 변경이랑 함께 수정했습니다!

2020-12-08 04:49 UTC, youngxpepp approved these changes, later dismissed
고생하셨습니다!

2020-12-08 04:52 UTC, dh00n submitted a review, later dismissed
👍👍👍👍👍

2020-12-08 06:56 UTC, dh00n approved these changes
👏👏👏👏👏

2020-12-08 07:11 UTC, youngxpepp approved these changes
오류 수정까지 고생하셨습니다!

2020-12-08 07:20 UTC, merged