Card C/D API 구현 (생성, 삭제)
boostcamp-2020/Project04-B-Whale pull request #236
Opened 2020-12-09 07:48 UTC by dh00n

# Card C/D API 구현 (생성, 삭제)

## 📎 해당 이슈

이슈 링크 (#197)

## 🛠 구현 내용 

- 카드 추가 api 구현
- 카드 삭제 api 구현
- 카드 CD api 테스트 구현

## 🙋‍ 리뷰어 참고 사항 
힘드시겠지만, 리뷰 부탁드리겠습니다 ! 😭 🙇

2020-12-10 03:46 UTC, Park-SooYeon approved these changes, later dismissed
수고하셨씁니다:)

2020-12-10 03:46 UTC, Park-SooYeon commented on server/src/service/CardService.js
> +            .getRawOne();
이런 쿼리는 쿼리빌더를 사용하는 것보다는 간단하게 find 함수를 사용할 수 있을 것 같아요!

2020-12-10 03:59 UTC, dh00n commented on server/src/service/CardService.js
> +            .getRawOne();
카드의 리스트 아이디를 가져와야 해서 조인 안하고 getRawOne 사용하려고 쿼리빌더 썼습니당 😭

2020-12-10 04:18 UTC, youngxpepp requested changes
리뷰 참고해주세요!

2020-12-10 04:18 UTC, youngxpepp commented on server/src/service/CardService.js
> +            .getRawOne();
```suggestion
        const card = await this.cardRepository
            .findOne(cardId, {
                loadRelationIds: {
                    relations: ['list'],
                    disableMixedMap: true,
                },
            })
```
위와 같이 하시면, 조인하지 않고 card.list.id에 값을 넣어줍니당

2020-12-10 04:18 UTC, youngxpepp commented on server/src/service/CardService.js
> +            .getRawOne();
list를 다시 조회하는거면 위에서 card를 조회할 때 조인으로 한번에 가져오는게 낫지 않을까요?
cardId에 해당하는 카드가 없다면 조인도 이루어지지 않을테니까 성능에도 문제 없을듯 합니다.

2020-12-10 04:18 UTC, youngxpepp commented on server/src/router/ListRouter.js
> +            dueDate: req.body.dueDate,
dueDate에 대한 검증이 이뤄지지 않네요
다른건 몰라도 dueDate에 대한 날짜 검증은 라우터 부분에서 해줘야 된다고 생각합니다

2020-12-10 04:18 UTC, youngxpepp commented on server/src/service/CardService.js
> +            .getRawOne();
리스트에 카드가 존재하지 않는다면 어떤 값이 반환되나요?

2020-12-10 04:18 UTC, youngxpepp commented on server/src/service/CardService.js
> +        await this.cardRepository.save(createCard);
```suggestion
        const card = this.cardRepository.create({
            title,
            content,
            position: cardWithMaxPosition.maxPosition + 1,
            dueDate,
            list: list.list_id,
            creator: userId,
        });
        await this.cardRepository.save(card);
```
변수를 하나 줄일 수 있는 방향이 좋다고 생각합니다

2020-12-10 04:43 UTC, dh00n commented on server/src/service/CardService.js
> +            .getRawOne();
오 이렇게도 되는군요 !
한가지 여쭤보고 싶은게 typeorm에서 쿼리빌더와 find메서드의 성능차이가 있나요?

2020-12-10 04:57 UTC, dh00n commented on server/src/service/CardService.js
> +            .getRawOne();
카드가 속한 리스트, 리스트가 속한 보드를 가져오려면 여러번 조인해야 해서, 
멘토님 피드백 이후로 끊어 보내는 것도 나쁘지 않겠다는 생각이 들었습니다 ㅎㅎ

2020-12-10 05:02 UTC, dh00n commented on server/src/service/CardService.js
> +            .getRawOne();
null 이 반환됩니다! 
이후에 null + 1 => 1로 position이 생성 됩니당

2020-12-10 06:12 UTC, dh00n commented on server/src/router/ListRouter.js
> +            dueDate: req.body.dueDate,
날짜 형식 말씀하시는 건가용??

2020-12-10 13:25 UTC, youngxpepp commented on server/src/service/CardService.js
> +            .getRawOne();
아... card.list로 가져오시면 조인을 하지 않겠네요. 조인을 하지 않는다면 성능차이는 없겠네요!

2020-12-10 13:41 UTC, youngxpepp commented on server/src/service/CardService.js
> +            .getRawOne();
카드 상세 조회나 보드 상세 조회 같이 복잡한 조인이 있을 때 끊어보내는 건 합리적이라고 생각해요.
카드 조회를 하고 만약 카드가 없다면 EntityNotFound 에러를 발생시켜서, 추가적인 리스트 조회가 이뤄지지 않도록 설계한건 좋은 생각입니다. 하지만 아래와 같이 작성하셔도 카드가 없을 때 조인이 일어나지 않습니다. 카드가 없기 때문이죵
```javascript
        const card = await this.cardRepository
            .createQueryBuilder('card')
            .innerJoinAndSelect('card.list', 'list')
            .where('card.id = :cardId', { cardId })
            .getOne();
```

2020-12-10 13:41 UTC, youngxpepp commented on server/src/router/ListRouter.js
> +            dueDate: req.body.dueDate,
넵 라우터에서의 검증 로직이 필요해 보여요

2020-12-10 15:12 UTC, dh00n commented on server/src/router/ListRouter.js
> +            dueDate: req.body.dueDate,
date 형식 검증 로직 추가하였습니당 !

2020-12-10 15:12 UTC, dh00n commented on server/src/service/CardService.js
> +            .getRawOne();
음   list.board도 가져오려면
```
 const card = await this.cardRepository
            .createQueryBuilder('card')
            .innerJoinAndSelect('card.list', 'list')
            .innerJoinAndSelect('list.board', 'board')
            .where('card.id = :cardId', { cardId })
            .getOne();
```
이렇게 짜야하지 않나요 ??

2020-12-11 03:07 UTC, Park-SooYeon approved these changes
수고하셨습니다:100:

2020-12-11 03:34 UTC, youngxpepp approved these changes
고생하셨습니다!!

2020-12-11 03:41 UTC, merged